# -*- coding: utf-8 -*-
DEBUG = True
# 把输出语句打印出来
SQLALCHEMY_ECHO = True
SQLALCHEMY_ENCODING = "utf-8"
SERVER_PORT = 9000
SQLALCHEMY_DATABASE_URI = 'mysql://root:root@127.0.0.1:3306/food_db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
AUTH_COOKIE_NAME = "mooc_food"
RELEASE__VERSION = "20230214001"
